#pragma once

/* Select hand configuration */

#define MASTER_LEFT
//#define MASTER_RIGHT
// #define EE_HANDS

#define TAPPING_FORCE_HOLD
#define TAPPING_TERM 175

#undef RGBLED_NUM
#define RGBLED_NUM 16
#define RGBLIGHT_EFFECT_BREATHING
#define RGBLIGHT_LIMIT_VAL 120
#define RGBLIGHT_HUE_STEP 10
#define RGBLIGHT_SAT_STEP 17
#define RGBLIGHT_VAL_STEP 17
#define RGBLIGHT_SPLIT
#define RGBLED_SPLIT { 8, 8 }


// Estos son necesarios sólo para que el oled non-master pueda leerlos
#define SPLIT_TRANSPORT_MIRROR
#define SPLIT_LAYER_STATE_ENABLE // Este es necesario para cambiar los rgb en slave segun la capa
//#define SPLIT_LED_STATE_ENABLE
//#define SPLIT_WPM_ENABLE


#define SPLIT_POINTING_ENABLE
#define POINTING_DEVICE_RIGHT

#define CIRQUE_PINNACLE_DIAMETER_MM 35
#define CIRQUE_PINNACLE_POSITION_MODE CIRQUE_PINNACLE_RELATIVE_MODE
#define CIRQUE_PINNACLE_TAP_ENABLE
// #define POINTING_DEVICE_GESTURES_CURSOR_GLIDE_ENABLE
//#define CIRQUE_PINNACLE_SECONDARY_TAP_ENABLE
#define POINTING_DEVICE_GESTURES_SCROLL_ENABLE
#define POINTING_DEVICE_ROTATION_270
